### ISSUE TITLE
Review CK8s deployment for golang to understand failed files

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/go-k8s-infra#120]

**Comment by naderaly** [comment]
@himanshu2464  @Lestat06 None of Minio, Jaeger, RabbitMQ or K8Dash are accessible in ck8s deployment is this intended as a security measure? 
FYI @GINAGC , other than that the failed files issue was resolved in this issue https://github.com/k8-proxy/go-k8s-infra/issues/119#issuecomment-874732603

**Comment by GINAGC** [comment]
@mahnouman please confirm the above.

**Comment by mahnouman** [comment]
Hello @GINAGC @naderaly those services: Minio, Jaeger, RabbitMQ or K8Dash, the exposure of them is not intended for production, they are for development and debugging, so it makes sense not to expose them in compliant Kubernetes version, though I am not sure that was by design of compliant Kubernetes

**Comment by GINAGC** [comment]
Ok, then let's review this in our meeting today.

**Comment by GINAGC** [comment]
Closing task
